language: php

sudo: required

branches:
  only:
    - v2.2-stable

addons:
  firefox: "47.0.1"
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.0
  - 7.1

env:
  global:
    - COVERAGE=false
  matrix:
    - MOODLE_BRANCH=MOODLE_32_STABLE DB=mysqli MOODLE_PLUGIN_CI=2
    - MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql MOODLE_PLUGIN_CI=2
    - MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli MOODLE_PLUGIN_CI=2
    - MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql MOODLE_PLUGIN_CI=2
    - MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli MOODLE_PLUGIN_CI=2
    - MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql MOODLE_PLUGIN_CI=2
    - MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli MOODLE_PLUGIN_CI=2
    - MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql MOODLE_PLUGIN_CI=2
    - MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli MOODLE_PLUGIN_CI=2
    - MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql MOODLE_PLUGIN_CI=2
    - MOODLE_BRANCH=master DB=mysqli MOODLE_PLUGIN_CI=2
    - MOODLE_BRANCH=master DB=pgsql MOODLE_PLUGIN_CI=2

matrix:
  include:
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=mysqli MOODLE_PLUGIN_CI=1
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql MOODLE_PLUGIN_CI=1
    - php: 5.5
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=mysqli MOODLE_PLUGIN_CI=1
    - php: 5.5
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql MOODLE_PLUGIN_CI=1
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=mysqli MOODLE_PLUGIN_CI=1
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql MOODLE_PLUGIN_CI=1
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli MOODLE_PLUGIN_CI=1
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql MOODLE_PLUGIN_CI=1
    - php: 5.5
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli MOODLE_PLUGIN_CI=1
    - php: 5.5
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql MOODLE_PLUGIN_CI=1
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli MOODLE_PLUGIN_CI=1
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql MOODLE_PLUGIN_CI=1
  exclude:
    - php: 7.0
      env: MOODLE_BRANCH=master DB=mysqli MOODLE_PLUGIN_CI=2
    - php: 7.0
      env: MOODLE_BRANCH=master DB=pgsql MOODLE_PLUGIN_CI=2

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  ## Standard script
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^${MOODLE_PLUGIN_CI}
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  ## Workaround for bypassing codechecker error due the use of BIGBLUEBUTTON_CFG
  - sudo sed -i "s/'MNET_REMOTE_CLIENT',/'MNET_REMOTE_CLIENT', 'BIGBLUEBUTTONBN_CFG',/g" "$(grep -rl MNET_REMOTE_CLIENT ./ci/vendor)"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  # Specific for version 1
  - if [ ${MOODLE_PLUGIN_CI} = "1" ]; then moodle-plugin-ci csslint; fi
  - if [ ${MOODLE_PLUGIN_CI} = "1" ]; then moodle-plugin-ci shifter; fi
  - if [ ${MOODLE_PLUGIN_CI} = "1" ]; then moodle-plugin-ci jshint; fi
  # Specific for version 2
  - if [ ${MOODLE_PLUGIN_CI} = "2" ]; then moodle-plugin-ci savepoints; fi
  - if [ ${MOODLE_PLUGIN_CI} = "2" ]; then moodle-plugin-ci mustache; fi
  - if [ ${MOODLE_PLUGIN_CI} = "2" ]; then moodle-plugin-ci grunt; fi
  - if [ ${MOODLE_PLUGIN_CI} = "2" ]; then moodle-plugin-ci behat; fi
